name: Deploy Elog-Hexo Public To Pages

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy Elog-Hexo Public To Pages
    runs-on: ubuntu-24.04  # 固定版本提高稳定性
    timeout-minutes: 20    # 防止卡死
    env:
      TZ: Asia/Shanghai
      # 保留所有环境变量（按需使用）
      YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
      YUQUE_LOGIN: ${{ secrets.YUQUE_LOGIN }}
      YUQUE_REPO: ${{ secrets.YUQUE_REPO }}
      YUQUE_USERNAME: ${{ secrets.YUQUE_USERNAME }}
      YUQUE_PWD: ${{ secrets.YUQUE_PWD }}
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
      FLOWUS_TABLE_PAGE_ID: ${{ secrets.FLOWUS_TABLE_PAGE_ID }}
      webpushrKey: ${{ secrets.WEBPUSHR_KEY }}
      webpushrAuthToken: ${{ secrets.WEBPUSHR_AUTH_TOKEN }}

    steps:
      # ===== 代码检出 =====
      - name: Checkout Code
        uses: actions/checkout@v4  # 固定版本
        with:
          ref: master
          fetch-depth: 1           # 浅克隆加速
          submodules: false

      # ===== Node环境设置 =====
      - name: Setup Node.js
        uses: actions/setup-node@v4
        id: setup-node
        with:
          node-version: "20"       # 固定LTS版本
          cache: "npm"             # 启用自动缓存
          check-latest: false      # 禁用自动更新（提高稳定性）

      # ===== 依赖安装 =====
      - name: Install Dependencies
        run: npm ci --prefer-offline  # 使用ci模式确保一致性
        env:
          NODE_ENV: production

      # ===== 内容下载 =====
      - name: Download Elog Posts
        uses: dawidd6/action-download-artifact@v4  # 升级到v4
        with:
          workflow: ${{ github.workflow }}  # 确保下载当前工作流的构件
          name: 'Elog Posts'
          path: 'source/_posts'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          if_no_artifact_found: warn

      - name: Download Elog Cache
        uses: dawidd6/action-download-artifact@v4
        with:
          workflow: ${{ github.workflow }}
          name: 'Elog Cache'
          path: 'elog'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          if_no_artifact_found: warn

      # ===== 生成静态站点 =====
      - name: Generate
        run: npm run elog
        env:
          CI: true  # 标记CI环境

      # ===== 构件上传 =====
      - name: Upload Elog Assets
        uses: actions/upload-artifact@v4
        with:
          name: 'Elog Assets'
          path: |
            elog/
            source/_posts/
          compression-level: 0  # 禁用压缩加速上传
          retention-days: 7      # 缩短保留时间
          if-no-files-found: warn

      # ===== 部署到posts分支 =====
      - name: Deploy Markdown Posts To Branch Posts
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: posts
          folder: ./source/_posts/
          force: false
          clean: true  # 清理目标目录
          git-config-name: "github-actions"
          git-config-email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit-message: "Content: ${{ github.sha }}"

      # ===== 部署到GitHub Pages =====
      - name: Deploy Hexo Public To Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: ./public
          repository-name: iosxx/iosxx.github.io  # 目标仓库
          token: ${{ secrets.GH_TOKEN }}
          clean: true
          single-commit: true  # 保持提交历史整洁

      # ===== 可选：部署到其他平台 =====
      #- name: Deploy to Bitbucket
      #  run: |
      #    cd ./public
      #    git init
      #    git config user.name "github-actions"
      #    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #    git add -A
      #    git commit -m "Deploy: ${{ github.sha }}"
      #    git push --force --quiet "https://ccknbc:${{ secrets.BB_TOKEN }}@bitbucket.org/ccknbc/ccknbc.bitbucket.io.git" master:master
      #
      #- name: Deploy to Coding
      #  run: |
      #    cd ./public
      #    git init
      #    git config user.name "github-actions"
      #    git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #    git add -A
      #    git commit -m "Deploy: ${{ github.sha }}"
      #    git push --force --quiet "https://${{ secrets.CD_USER }}:${{ secrets.CD_TOKEN }}@e.coding.net/ccknbc/blog/butterfly.git" master:master
